package com.example.rsq.ai.model

/**
 * Represents a severity prediction generated by an AI model.
 *
 * @property severity The predicted severity level (e.g., LOW, MEDIUM, HIGH, CRITICAL).
 * @property confidence A value between 0.0 and 1.0 representing the model's confidence in the prediction.
 * @property reason A brief explanation or justification for the assigned severity.
 */
data class SeverityPrediction(
    val severity: String,
    val confidence: Float,
    val reason: String
)
